### ISSUE TITLE
No json folder anymore

### ISSUE THREAD

**Issue by tinganho** [rxaviers/cldr-data-npm#10]
@rxaviers I just saw that the build script doesn't build a `json` folder anymore? So it broke l10ns.

**Comment by rxaviers** [comment]
Removing the json folder allowed `require( "cldr-data/<path>" )` instead of `require( "cldr-data" )( "<path>" )`.

Were you using `require( "cldr-data/json/<path>" )`? Can you update it by removing the json from your paths?

**Comment by tinganho** [comment]
@rxaviers I will update it later.

**Comment by rxaviers** [comment]
Ok and sorry for the inconvenience. Ideally, this project was using semver. But, in order to track CLDR versions I had to stick with major and minor for CLDR and patch for whatever changes for this project.
