### ISSUE TITLE
language detected. 

### ISSUE THREAD

**Issue by martingg88** [rxaviers/cldr-data-npm#14]
how can i find the main language used for specific country. 

For example if i give "US" as country code. 
what is the method/files i need to find the main language for "US" country?

**Comment by rxaviers** [comment]
Take a look at [supplemental/territoryInfo](https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/territoryInfo.json).

**Comment by martingg88** [comment]
try to review the file. in between, i realize one country may have more than one languagePopulation, so which one of language is more reliable to pick up for specific country?

**Comment by rxaviers** [comment]
You'll notice there's a field `populationPercent` that shows the most used one per territory. Please, just let me know in any further questions.

**Comment by martingg88** [comment]
cool. but the language code is not consistent in \main\ms-Latn\languages.json. 

as we know 'ms_Latn' could be the main language for MY country. However we may not find any 'ms_Latn' in  \main\ms-Latn\languages.json (note: refer to localeDisplayNames.languages). Thus we may have some issue to find/match language in any part of project. any idea how to solve this issue?

      "MY": {
        "_gdp": "525000000000",
        "_literacyPercent": "93.1",
        "_population": "30073400",
        "languagePopulation": {
          "ms_Latn": {
            "_officialStatus": "official",
            "_populationPercent": "75"
          },
      },

**Comment by rxaviers** [comment]
> However we may not find any 'ms_Latn' in \main\ms-Latn\languages.json

No, because `ms-Latn` means `ms` language, `Latn` script. Therefore, you look for `ms` in there.

I suggest you use https://github.com/rxaviers/cldrjs for traversing the data. By using cldrjs, you can:

    npm install cldr-data cldrjs

```js
var Cldr = require("cldrjs");
Cldr.load(require("cldr-data/main/ms-Latn/languages"));

var cldr = new Cldr("ms-Latn");
cldr.main("localeDisplayNames/languages/{language}");
// > 'Bahasa Melayu'
```

**Comment by martingg88** [comment]
ok...thanks.

**Comment by martingg88** [comment]
@rxaviers i do have one question here. thanks. 

how to make sure this ISO format (etc: language-country/en-US) is apply to my project by using this cldr data library?

I feel strange cldr data doesn't follow this format as some languages do not append with country code.

**Comment by rxaviers** [comment]
@martingg88 I didn't understand your question? Could you reformulate it please?

**Comment by martingg88** [comment]
i realize that cldr doesn't stick to one ISO format as it may come with several possibilities for language code as for example below: 

1. en
3. en-US
2. ms

how to make sure it always follow this format ?

1. language code - country code (etc: en-US, en-GB)

**Comment by rxaviers** [comment]
I recommend reading [What is a Locale?](http://www.unicode.org/reports/tr35/#Locale) :)

**Comment by rxaviers** [comment]
If you are using cldrjs, it takes care of the normalization for you. For example,

```js
var Cldr = require("cldrjs");
Cldr.load(require("cldr-data/supplemental/likelySubtags")); // Note you need to load likelySubtags.
Cldr.load(require("cldr-data/main/en/languages"));

var cldr = new Cldr("en");
cldr.main("localeDisplayNames/languages/{language}");
// > 'English'

var cldr = new Cldr("en-US");
cldr.main("localeDisplayNames/languages/{language}");
// > 'English'

var cldr = new Cldr("en-Latn");
cldr.main("localeDisplayNames/languages/{language}");
// > 'English'

var cldr = new Cldr("en-Latn-US");
cldr.main("localeDisplayNames/languages/{language}");
// > 'English'
```

**Comment by martingg88** [comment]
many thanks for your answer.

1. var cldr = new Cldr("en-US");

this should produce "American English" instead. It make more sense than "English". right?

2. last question here.

a. i'm trying to generate a list of language (that is supported by cldr data) for selection purpose.
b. i will not get standard language ISO format if i based on cldr.main("localeDisplayNames/languages"
). 
c. what can i do to generate a list that its language code will follow ISO format (etc: language code-country code)?

    en-US = "America English"
    en-GB = "UK English"
   ms-MY = "Bahasa Melayu"

**Comment by rxaviers** [comment]
It's very easy to accomplish what you want by iterating over the whole `localeDisplayNames/languages`. I don't know what you mean by "language ISO format".

**Comment by martingg88** [comment]
but some of languages do not follow this format.
 (language code-country code) refer to ISO format.

any idea how to make sure all languages follow this format
 (language code-country code) 
 (etc: en-US)

**Comment by rxaviers** [comment]
Does it help you?


```js
var locale = "en";
var Cldr = require("cldrjs");
Cldr.load(require("cldr-data/main/en/languages"));

var cldr = new Cldr(locale);

cldr.main("localeDisplayNames/languages");
// > { aa: "Afar",
//     ab: "Abkhazian",
//     ...
//   }

Object.keys(cldr.main("localeDisplayNames/languages")).map(function(locale) {
  return cldr.main(["localeDisplayNames/languages", locale]);
});
// > [ "Afar",
//     "Abkhazian",
//     ...
//   ]
```

**Comment by martingg88** [comment]
i should be able to generate list like following. But my question is how to make left hand side which is language code to follow this format (language_code-country_code)? so i should expect all the language code in following list should be appended with country code (etc: en-US, en-GB, en-SG).

{
 aa: "Afar",
 ab: "Abkhazian",
 ...
}

**Comment by rxaviers** [comment]
@martingg88 I hope all the above makes it clear on how you could accomplish what you need.

**Comment by martingg88** [comment]
anyway. thanks for your effort.
