### ISSUE TITLE
error on npm install

### ISSUE THREAD

**Issue by chrisdrackett** [rxaviers/cldr-data-npm#15]
I'm running into the following when trying to install with npm:

```
> node install.js

GET `https://github.com/unicode-cldr/cldr-core/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-dates-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-cal-buddhist-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-cal-chinese-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-cal-coptic-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-cal-dangi-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-cal-hebrew-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-cal-indian-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-cal-islamic-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-cal-japanese-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-cal-persian-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-cal-roc-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-localenames-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-misc-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-numbers-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/27.0.3.zip`
GET `https://github.com/unicode-cldr/cldr-units-modern/archive/27.0.3.zip`
  [----------------------------------------] 3672/Infinity 0% 0.0s/Users/cwd/src/AnswerDash/Qazzow/sales_dashboard/node_modules/cldr-data/node_modules/cldr-data-downloader/lib/download.js:51
      throw error;
            ^
Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at TLSSocket.socketOnEnd (_http_client.js:300:23)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "cldr-data"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! cldr-data@27.0.5 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cldr-data@27.0.5 install script 'node install.js'.
npm ERR! This is most likely a problem with the cldr-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls cldr-data
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cwd/src/AnswerDash/Qazzow/sales_dashboard/npm-debug.log```

**Comment by rxaviers** [comment]
Why are you running it manually (not via `npm install cldr-data`)?

**Comment by rxaviers** [comment]
Anyway, it works for me. I could not reproduce the bug you're observing. Can you provide more details please? So, we can understand the cause of the issue for you.

**Comment by chrisdrackett** [comment]
seems to be working now, maybe it was a temp server issue.

**Comment by rxaviers** [comment]
Thanks

**Comment by prshnth** [comment]
@rxaviers any suggestions?

C:\Users\p595379>npm install cldr-data
-
> cldr-data@28.0.2 install C:\Users\p595379\node_modules\cldr-data
> node install.js

GET `https://github.com/unicode-cldr/cldr-core/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-dates-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-buddhist-modern/archive/28.0.0.zip
`
GET `https://github.com/unicode-cldr/cldr-cal-chinese-modern/archive/28.0.0.zip`

GET `https://github.com/unicode-cldr/cldr-cal-coptic-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-dangi-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-modern/archive/28.0.0.zip
`
GET `https://github.com/unicode-cldr/cldr-cal-hebrew-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-indian-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-islamic-modern/archive/28.0.0.zip`

GET `https://github.com/unicode-cldr/cldr-cal-japanese-modern/archive/28.0.0.zip
`
GET `https://github.com/unicode-cldr/cldr-cal-persian-modern/archive/28.0.0.zip`

GET `https://github.com/unicode-cldr/cldr-cal-roc-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-localenames-modern/archive/28.0.0.zip`

GET `https://github.com/unicode-cldr/cldr-misc-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-numbers-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-units-modern/archive/28.0.0.zip`
C:\Users\p595379\node_modules\cldr-data\node_modules\cldr-data-downloader\lib\do
wnload.js:51
      throw error;
      ^

Error: connect ETIMEDOUT 
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "cldr-data"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! cldr-data@28.0.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cldr-data@28.0.2 install script 'node install.js'.
npm ERR! This is most likely a problem with the cldr-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls cldr-data
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\p595379\npm-debug.log

C:\Users\p595379>

**Comment by clazette** [comment]
@prshnth did you ever get this resolved? I am having the same issue for clr-data@28.0.5.

**Comment by prshnth** [comment]
I think it was a temp issue, got fixed after a while.

**Comment by rxaviers** [comment]
@clazette does it persists to you? Is it related to https://github.com/rxaviers/cldr-data-downloader/issues/19?
