### ISSUE TITLE
cldr-data does not install in an enterprise environment

### ISSUE THREAD

**Issue by UnrememberMe** [rxaviers/cldr-data-npm#20]
Similar to  https://github.com/karma-runner/karma/issues/1424,  cldr-data is pulling directly from github for some of its dependencies.  I believe urls.json contains the direct reference.  The installation failed for me when I tried to run npm install in a datacenter where machines do not have external network connectivity.

**Comment by rxaviers** [comment]
> where machines do not have external network connectivity

Am I missing anything, but without network connectivity you cannot install any public package right?

**Comment by alunny** [comment]
@rxaviers - @UnrememberMe works with me :)

We install the public packages from our artifactory instance, which mirrors the npm registry.

If we can't publish the cldr-data to npm, we'd want to modify the install script to pull from an internal endpoint instead of github.com.

**Comment by rxaviers** [comment]
We could come up with a package.json property that modifies the url source where cldr-data-npm fetches data from. The property usage would be similar to `cldr-data-coverage` (https://github.com/rxaviers/cldr-data-npm#locale-coverage) and we somehow change https://github.com/rxaviers/cldr-data-npm/blob/master/urls.json dynamically.

Would that work?

FWIW, cldr-data-npm uses https://github.com/rxaviers/cldr-data-downloader to download.

**Comment by UnrememberMe** [comment]
This should work.  We can host the required .zip files on our own server and redirect the download to that server using the environment variable.  As this example shows "CLDR_COVERAGE=full npm install"

**Comment by rxaviers** [comment]
> This should work. We can host the required .zip files on our own server and redirect the download to that server using the environment variable. As this example shows "CLDR_COVERAGE=full npm install"

Excellent. Yeap, it should work either by setting a an environment variable or by using a npm config.

The implementation would be analogous to https://github.com/rxaviers/cldr-data-npm/blob/master/install.js#L65-L78. I would be happy to merge a PR implementing it. Please, just let me know on any questions.

**Comment by dijonkitchen** [comment]
Is this still relevant or should it be closed?

**Comment by rxaviers** [comment]
@dijonkitchen, thanks for asking...

In order to load CLDR from inside the intranet, I suggest to use the existing CLDR_DATA_URLS_JSON where you can pass a custom array of urls.
