### ISSUE TITLE
postalCodeData is no longer present in unicode-cldr 28.0

### ISSUE THREAD

**Issue by alunny** [rxaviers/cldr-data-npm#21]
`postalCodeData` is no longer present here:
https://github.com/unicode-cldr/cldr-core/tree/28.0.0/supplemental

Because of this, `index.js` fails to run since, it tries to require this file:
https://github.com/rxaviers/cldr-data-npm/blob/master/index.js#L23

**Comment by rxaviers** [comment]
I have a feeling that these files should be listed dynamically instead of having their names hardcoded here. I've noticed they are not exactly the same among the various locales. But, never had a chance to improve this code.

**Comment by alunny** [comment]
I can take a stab at that.
