### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by martingg88** [rxaviers/cldr-data-npm#26]
do u have any idea about this issue?

my node version is v5.2.0  and npm is 3.3.12

> cldr-data@28.0.3 install C:\project\ctx\lib\node_modules\cldr-data
> node install.js

GET `https://github.com/unicode-cldr/cldr-core/archive/28.0.2.zip`
GET `https://github.com/unicode-cldr/cldr-dates-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-buddhist-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-chinese-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-coptic-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-dangi-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-hebrew-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-indian-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-islamic-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-japanese-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-persian-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-roc-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-localenames-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-misc-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-numbers-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-units-modern/archive/28.0.0.zip`
  [----------------------------------------] 4344641/Infinity 0% 0.0sC:\project\ctx\lib\node_modules\cldr-data-dow
nloader\lib\download.js:51
      throw error;
      ^

Error: 101057795:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:openssl\ssl\s3_pk
t.c:532:

 cldr-data@28.0.3 install: `node install.js`
 Exit status 1

 Failed at the cldr-data@28.0.3 install script 'node install.js'.
 Make sure you have the latest version of node.js and npm installed.
 If you do, this is most likely a problem with the cldr-data package,
 not with npm itself.
 Tell the author that this fails on your system:
     node install.js
 You can get their info via:
     npm owner ls cldr-data
 There is likely additional logging output above.

**Comment by rxaviers** [comment]
Do you keep getting this error? Does it also fail with different node or npm versions? I could not reproduce.

**Comment by martingg88** [comment]
lets close this issue for now. will get you back if i have this issue again. thanks

**Comment by martingg88** [comment]
i think the error as follows: 

Error: 101057795:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:openssl\ssl\s3_pk
t.c:532:

**Comment by rxaviers** [comment]
I cannot reproduce this error, because I don't use Windows. Sorry. Although, I am open to accept PRs fixing it.
