### ISSUE TITLE
Missing en-US

### ISSUE THREAD

**Issue by bimusiek** [rxaviers/cldr-data-npm#27]
Hey,

we are investigating why we cannot localize `en-US` and it happens that it cannot be found in `cldr-data-npm` as it exists with `-POSIX` subfix. 

I checked http://www.unicode.org/Public/cldr/28/ and I can find there .xml for `en-US` and for `en-US-POSIX`. 

Any reason why it is not a part of `cldr-data`? 
Also, if this is correct behaviour, what would be the best solution to properly load this -POSIX data? 

Cheers, Mike.

**Comment by rxaviers** [comment]
Hi,

Short answer: load `en`, which means English (United States region and Latin script are deduced given they are respectively the most likely region and script used in this place).

If you are using https://github.com/rxaviers/cldrjs or https://github.com/jquery/globalize/, they are smart to correctly instantiate `new Cldr('en-US')` or `new Cldr('en-Latn-US')` or `new Cldr('en)`after you having loaded the `en` bundle.

Longer answer: http://www.unicode.org/reports/tr35/tr35-info.html#Default_Content, https://github.com/jquery/globalize/#locales

**Comment by rxaviers** [comment]
Please, just let me know if you have any further question.
