### ISSUE TITLE
local files overwritten, 'git status' not clean after 'npm i'

### ISSUE THREAD

**Issue by srl295** [rxaviers/cldr-data-npm#37]
Tried both v29 and the PR'ed #36 (v30)

Following aren't .gitignored:

	.gitattributes
	.ignored-bower.json
	.ignored-package.json
	LICENSE
	availableLocales.json
	defaultContent.json
	main/
	scriptMetadata.json
	segments/
	state.json
	supplemental/

And also, `README.md` and `.gitignore` get replaced (probably from CLDR contents)

**Comment by rxaviers** [comment]
Thank you
