### ISSUE TITLE
Improve downloads filtering

### ISSUE THREAD

**Issue by puzrin** [rxaviers/cldr-data-npm#44]
[Current method](https://github.com/rxaviers/cldr-data-npm#set-custom-json-file-with-urls) to restrict download via `package.json` has some disadvantages:

1. It requires additional json file (not convenient) with relative path (strange).
2. It freeze url versions. User should care about file versions update even after package was updated.

I'd suggest add support for regexp:

```json
{
   "cldr-data-urls-filter": "(cldr-core|cldr-dates-modern|cldr-numbers-modern)"
}
```

I think that would be more simple and convenient for all.

**Comment by rxaviers** [comment]
LGTM, feel free to submit a PR.
