### ISSUE TITLE
Installation error with 29.0.0

### ISSUE THREAD

**Issue by jzaefferer** [rxaviers/cldr-data-npm#47]
I'm aware there's a bunch of open issues related to install (not suprising, since this package doesn't really do anything else), but since they all look like slightly different issues and are more or less old, I'm creating a new one.

After about 10 attempts, I'm still getting a failure while trying to install cldr-data:
```
$ npm install
> cldr-data@29.0.2 install /Users/joern.zaefferer/dev/sloppy/frontend/node_modules/cldr-data
> node install.js

GET `https://github.com/unicode-cldr/cldr-core/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-dates-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-buddhist-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-chinese-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-coptic-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-dangi-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-hebrew-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-indian-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-islamic-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-japanese-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-persian-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-roc-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-localenames-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-misc-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-numbers-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/29.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-units-modern/archive/29.0.0.zip`
  [----------------------------------------] 21867380/Infinity 0% 0.0s/workdir/node_modules/cldr-data-downloader/lib/download.js:51
      throw error;
      ^

Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! cldr-data@29.0.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cldr-data@29.0.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cldr-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cldr-data
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cldr-data
npm ERR! There is likely additional logging output above.
```
I wondered if any specific package under https://github.com/unicode-cldr might be at fault, but since there are so many and the output doesn't tell me which one is reponsible, I gave up on that.

**Comment by rxaviers** [comment]
Interesting... I also see that and I would guess https://github.com/unicode-cldr to be at fault too.

One workaround for now is to reduce the set of files you should download, see https://github.com/globalizejs/globalize/blob/master/examples/node-npm/package.json#L9

**Comment by rxaviers** [comment]
Even that is failing. Downloads stall...

**Comment by vhinterview** [comment]
I'm hitting this as well on cldr-data@30.0.4

**Comment by bgeihsgt** [comment]
I am hitting this as well on `cldr-data@30.0.4`

**Comment by Retsam** [comment]
My team is also seeing it on 30.0.3.  

This wouldn't be hurting us so badly if it didn't redownload all the data every time we did an install.  Is there documentation on how to get the data to cache between installs?

**Comment by FelikZ** [comment]
I think this is similar to #15 #25

**Comment by jzaefferer** [comment]
> Is there documentation on how to get the data to cache between installs?

As far as I can tell, once the package is installed, it won't download anything again.

**Comment by zachelrath** [comment]
I agree with @rxaviers, I think the issue is just that Github has not fully recovered from its [service disruption this morning](https://status.github.com/graphs/past_day). We're still seeing periodic 502's and timeouts from https://github.com/unicode-cldr.

**Comment by Retsam** [comment]
> As far as I can tell, once the package is installed, it won't download anything again.

Not the behavior I've seen; if I run `npm install` twice it downloads the files twice.  (Same for `yarn`)

**Comment by jzaefferer** [comment]
Looks like this was indeed an issue on GitHub's side. https://status.github.com/graphs/past_day says everything is back to normal now, and I could just complete the install.

Since I opened the issue, I'll close it.

PS: Once successfully installed, further `npm install` calls don't trigger the download again.

**Comment by jjarcik** [comment]
Use yarn instead of npm helped me today.
