### ISSUE TITLE
npm install fails 

### ISSUE THREAD

**Issue by mjacob4813** [rxaviers/cldr-data-npm#54]
cldr-data@31.0.0/31.0.1/31.0.2 all fails when installing node modules.

316 silly saveTree └─┬ xml2js@0.4.19
316 silly saveTree   ├── sax@1.2.4
316 silly saveTree   └── xmlbuilder@9.0.4
317 warn bootstrap@4.0.0 requires a peer of popper.js@^1.12.9 but none is installed. You must install peer dependencies yourself.
318 verbose stack Error: cldr-data@31.0.2 install: `node install.js`
318 verbose stack Exit status 1
318 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
318 verbose stack     at emitTwo (events.js:126:13)
318 verbose stack     at EventEmitter.emit (events.js:214:7)
318 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
318 verbose stack     at emitTwo (events.js:126:13)
318 verbose stack     at ChildProcess.emit (events.js:214:7)
318 verbose stack     at maybeClose (internal/child_process.js:925:16)
318 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
319 verbose pkgid cldr-data@31.0.2
320 verbose cwd /Users/<>/Documents/Code/COE/MFSG
321 verbose Darwin 17.4.0
322 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cldr-data@31.0.2"
323 verbose node v8.9.4
324 verbose npm  v5.6.0
325 error code ELIFECYCLE
326 error errno 1
327 error cldr-data@31.0.2 install: `node install.js`
327 error Exit status 1
328 error Failed at the cldr-data@31.0.2 install script.
328 error This is probably not a problem with npm. There is likely additional logging output above.
329 verbose exit [ 1, true ]

**Comment by rxaviers** [comment]
Dup of #49
