### ISSUE TITLE
Filter installed locales

### ISSUE THREAD

**Issue by vincent-tr** [rxaviers/cldr-data-npm#57]
Hi,

When I install cldr-data, the `node_modules/cldr-data` folder is about 260Mb.
It seems that it is split into a huge number of locales, and each locale folder is around 900kb.

I only want to support a few locales in my project.
Is there any way to filter locales and only get a few on install ?

Thanks

**Comment by rxaviers** [comment]
The two "cldr-data-coverage" options are "modern" and "full". This is a direct mapping with that CLDR offers...
