### ISSUE TITLE
new line on each interval during install

### ISSUE THREAD

**Issue by tinganho** [rxaviers/cldr-data-npm#7]
I somehow got new lines whenever I install `cldr-data`. It happens directly after the download:

![screen shot 2015-02-19 at 4 59 47 pm](https://cloud.githubusercontent.com/assets/1324476/6263894/dfbd1344-b858-11e4-9a02-54a4300ac256.png)

**Comment by tinganho** [comment]
Ok found the issue, `request-progress` is sometimes receiving more than total packages and thus over ticking. 

The issue is fixed on cldr-data-downloader:
https://github.com/rxaviers/cldr-data-downloader/pull/13

**Comment by rxaviers** [comment]
Excellent, thank you.
